[tool.poetry]
name = "fastapi-log-analyzer"
version = "1.0.0"
description = "Log analyzer with FastAPI and Celery"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0.0"
torch = "2.2.1"
sentence-transformers = "2.5.0"
uvicorn = "0.27.1"
fastapi = "0.110.0"
celery = {version = "5.3.4", extras = ["redis"]}
python-dotenv = "1.0.1"
flower = "2.0.1"
google-generativeai = "^0.8.5"
google-genai = "^1.26.0"
sqlalchemy = "^2.0.41"
psycopg2-binary = "^2.9.10"
alembic = "^1.16.4"
eventlet = "^0.40.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"